Code:
  - changed-files:
    - any-glob-to-any-file: code/**/*

Mapping:
  - changed-files:
    - any-glob-to-any-file: maps/**/*

Github:
  - changed-files:
    - any-glob-to-any-file: .github/**/*

Sprites:
  - changed-files:
    - any-glob-to-any-file: icons/**/*

Tools:
  - changed-files:
    - any-glob-to-any-file: tools/**/*

TGUI:
  - changed-files:
    - any-glob-to-any-file: tgui/**/*

Sounds:
  - changed-files:
    - any-glob-to-any-file: sounds/**/*
