#pretending we're C because otherwise ruby will initialize, even with "language: dm".
language: generic
sudo: false

git:
  depth: 1

env:
  global:
    - BYOND_MAJOR="514"
    - BYOND_MINOR="1557"
    - BYOND_MACRO_COUNT=2
  matrix:
    - DM_MAPFILE="_map_include"

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}

addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386

before_script:
  - chmod +x ./install-byond.sh
  - ./install-byond.sh
script:
  - (num=`grep -E '\\\\(red|blue|green|black|italic|bold|b|i[^mc])' **/*.dm | wc -l`; echo "$num BYOND text macros (expecting ${BYOND_MACRO_COUNT} or fewer)"; [ $num -le ${BYOND_MACRO_COUNT} ])
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - bash dm.sh -M${DM_MAPFILE} baystation12.dme
