/obj/item/paper/dclass_orientation
	name = "Class-D Orientation Letter"
	info = "<small>Greetings,<br><br>On behalf of all staff within The Foundation, we welcome you to Site-53. You have chosen, or been chosen for the honor of joining the Foundation Rehabilitation Program. During your thirty day stay within this facility, you will be known as Class-D personnel, and be given a unique numerical designation for ease of access, which has been printed on your new ID card. <br><br>Over the course of your stay here, you will undergo various programs to ensure that you are ready to re-enter the world again. You will be given the opportunity to select a job within your block, in order to assist your fellow D-Class. From working the kitchen, to digging out objects within our mining area. On top of this, you may be selected for various medical or research tests to assist in our projects. What are those projects? Unfortunately, we can't tell you that.<br><br>Given that you are cooperative with our staff for the entirety of your stay here, you will be released back into the world, and have your criminal record erased completely. With that being said, we hope that you enjoy your stay here.<br><br>Sincerely,<br>The Administrator</small>"
	desc = "A laminated piece of paper given to D-Class personnel upon their arrival."

/obj/item/paper/commsbriefing
	name = "Communications Relay Reminder"
	info = "<large><b><i><loglogo>Communications Relay Reminder</i></b></large><br>Admins been getting on us to use the proper communications channels, so they set you up with a communications relay you'll find on the right side of the tower where the old fax machine is. I mean.. really the relay's just a <i>souped up</i> fax machine but remember these key points.<br><list>-This is the <b>only</b> fax machine that can make outbound communications in the facility.<br>-Yes, you'll have to deal with various administrative personnel asking you to forward a fax..no you should <b>not</b> read confidential documents.<br>-<u>Remember to check in at the fax machine occasionally</u> to see if any new priority communications have come in, and fax them to the correct office if need be.<br>-In the inevitable event that personnel complain about not being able to send their own faxes, feel free to remind them of how important operational security is to admin, or send them this fax. <br>Warmest regards, <i>Overwatch Communications</i></list>"
	desc = "A small piece of paper that seems to be reminding you to use the proper communication relay for outbound transmissions."
