GLOBAL_LIST_EMPTY(trusted_players) //CKeys of trusted players.

GLOBAL_LIST_EMPTY(reagents_datums)

// A global list of all available spell categories
GLOBAL_LIST_INIT(spell_categories, list(
	SPELL_CATEGORY_FIRE,
	SPELL_CATEGORY_EXPLOSIVE,
	SPELL_CATEGORY_HEALING,
	SPELL_CATEGORY_MOBILITY,
	SPELL_CATEGORY_PASSIVE,
	SPELL_CATEGORY_ANTIMAGIC,
	SPELL_CATEGORY_FORBIDDEN,
	))
