name: 'Check for merge conflicts'
on:
  push:
    branches:
      - dev
      - 'project/**'
jobs:
  triage:
    runs-on: ubuntu-20.04
    steps:
      - uses: mschilde/auto-label-merge-conflicts@591722e97f3c4142df3eca156ed0dcf2bcd362bd
        with:
          CONFLICT_LABEL_NAME: 'Merge Conflict'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WAIT_MS: 10000
