name: Make and compile changelogs

on:
  push:
    branches:
      - dev

jobs:
  MakeCL:
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[ci skip]')"
    steps:
      - name: Checkout
        uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b
        with:
          fetch-depth: 0
          ref: dev
          token: ${{ secrets.BOT_TOKEN }}
      - name: Python setup
        uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5
        with:
          python-version: "3.9"
      - name: Install depends
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/changelog/requirements.txt
          python -m pip install pyyaml
          sudo apt-get install  dos2unix
      - name: Make CL
        env:
          GITHUB_TOKEN: ${{ secrets.BOT_TOKEN }}
          GIT_EMAIL: "${{ secrets.BOT_EMAIL }}"
          GIT_NAME: "${{ secrets.BOT_USERNAME }}"
        run: python tools/changelog/generate_cl_local.py
      - name: Compile CL
        run: |
          python tools/changelog/ss13_genchangelog.py html/changelogs
      - name: Commit And Push
        run: |
          git config --global user.email "${{ secrets.BOT_EMAIL }}"
          git config --global user.name "${{ secrets.BOT_USERNAME }}"
          git diff --quiet --exit-code && echo "No changes found, abort." && exit 0
          git pull origin dev
          git add html/changelogs
          git commit -m "Automatic changelog generation and compile [ci skip]" -a
          git push